services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node API service
  api:
    build: .                    # Builds the image from the Dockerfile in the current directory
    image: nodeapp
    container_name: node_api
    ports:
      - "3030:3030"
    depends_on:
      - mongo_db
    restart: always

volumes:
  mongo_data:
